again

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,21 +1,53 @@
 #!/bin/bash
+cd /tmp/rom # Depends on where source got synced
+rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur
 
-cd /tmp/rom
-
-git clone https://github.com/Redmi-MT6768/android_vendor_xiaomi_lava -b eleven vendor/xiaomi/lava
-git clone https://github.com/zubairk22oct/Device_Xiaomi_Lava -b Havoc-11 device/xiaomi/lava
-bash device/xiaomi/lava/vendorsetup.sh
-
+# Normal build steps
 . build/envsetup.sh
 lunch havoc_lava-userdebug
 export CCACHE_DIR=/tmp/ccache
 export CCACHE_EXEC=$(which ccache)
 export USE_CCACHE=1
-ccache -M 60G
-ccache -o compression=true
-ccache -z
+ccache -M 60G # It took only 6.4GB for mido
+ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
+ccache -z # Clear old stats, so monitor script will provide real ccache statistics
 
-make api-stubs-docs
-make system-api-stubs-docs
-make test-api-stubs-docs
-mka bacon -j10
+# Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines
+#make api-stubs-docs || echo no problem
+#make hiddenapi-lists-docs || echo no problem
+#make system-api-stubs-docs || echo no problem
+#make test-api-stubs-docs || echo no problem
+#make aex -j8 &
+#sleep 100m
+#kill $(pidof soong_ui)
+#kill $(pidof make)
+#and dont use below codes for first 1 or 2 times, to get ccache uploaded,
+
+
+# upload function for uploading rom zip file! I don't want unwanted builds in my google drive haha!
+up(){
+	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
+	# 14 days, 10 GB limit
+}
+
+# Build command! j10 for 10 cpu, j8 for 8 cpu, otherwise memeroy will end up even its 24G
+# Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!
+
+# Let's compile by parts! Coz of ram issue!
+make api-stubs-docs -j10
+make system-api-stubs-docs -j10
+make test-api-stubs-docs -j10
+
+export SELINUX_IGNORE_NEVERALLOWS=true
+echo "#!/bin/bash" >> bruh.sh
+echo "export SELINUX_IGNORE_NEVERALLOWS=true" >> bruh.sh 
+echo ". build/envsetup.sh" >> bruh.sh
+echo "lunch havoc_lava-userdebug" >> bruh.sh
+echo "make bacon -j10" >> bruh.sh
+
+timeout -k 5400 bash bruh.sh 
+
+if [[ ($ls out/target/product/* | grep .zip) ]]; then 
+	cd out/target/product/*
+	curl --upload-file *.zip https://transfer.sh/
+fi
